[package]
name = "avltree"
version = "0.1.0"
authors = ["Gabriela Alexandra Moldovan <gabi_250@live.com>"]
description = "A very simple AVL tree implementation"
readme = "README.md"
license = "GPL-3.0-or-later"

[dependencies]
rand = "0.3"

[features]
default = []
